name: CI
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  dev:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn affected:build --base=dev --head=HEAD --parallel=5
