name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
      - test/cicd
  pull_request:
    branches:
      - dev
      - master
      - test/cicd

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.13.0]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Verify Yarn Installation
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      # - name: Run lint
      #   run: yarn lint

      # - name: Run tests
      #   run: yarn affected:test

      - name: Build project
        run: yarn affected:build

      - name: List build directory contents
        run: ls -al

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: soaf_front/services/soaf/dist/**

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/test/cicd'

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: soaf_front/services/soaf/dist/

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          S3_BUCKET: "soaf-pront"
        run: |
          npm install -g aws-cli
          aws s3 sync dist/ s3://$S3_BUCKET --acl public-read
